### ISSUE TITLE
Ads are not loaded on route change for UI-ROUTER

### ISSUE THREAD

**Issue by yogiswar1987** [Stegoo/angular-google-adsense#5] opened 2016-08-08 04:58 UTC
Ad loads once the page loads, On navigation to other routes with Ad, ads are not displayed with error
angular.js:13920 TagError: adsbygoogle.push() error: No slot size for availableWidth=0

**Comment by Stegoo** [comment] 2016-08-08 17:45
Hey could you provide a plunkr please :) ?

**Comment by Stegoo** [comment] 2016-09-13 15:22
Duplicate of #6 . Feel free to reopen it if I'm mistaken.

**Closed as completed by Stegoo** 2016-09-13 15:22 UTC
